In [2]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.options import Options

In [3]:
def set_chrome_options() -> None:
    """Sets chrome options for Selenium.
    Chrome options for headless browser is enabled.
    """
    chrome_options = Options()
    chrome_options.add_argument("--headless")
    chrome_options.add_argument("--no-sandbox")
    chrome_options.add_argument("--disable-dev-shm-usage")
    chrome_prefs = {}
    chrome_options.experimental_options["prefs"] = chrome_prefs
    chrome_prefs["profile.default_content_settings"] = {"images": 2}
    return chrome_options

In [4]:
chrome_options = set_chrome_options()
driver = webdriver.Chrome(options=chrome_options)

global driver

In [5]:
def connect_to_url(url):
    return driver.get(url)

url = 'https://scores.nbcsports.com/golf/final.asp?tour=PGA'
connect_to_url(url)

In [7]:
def get_scoreboard_table():
    return driver.find_elements(By.TAG_NAME, "table")[1]
    
table = get_scoreboard_table()

In [9]:
def get_table_rows(table):
    return table.find_elements(By.TAG_NAME, 'tr')
    
trs = get_table_rows(table)

In [11]:
%%time

scoreboard = []

for tr in trs:
    if tr.get_attribute('class') not in ['shsTableTtlRow', 'shsTableSubttlRow', 'shsColTtlRow']:
        player_score = {}
        tds = tr.find_elements(By.TAG_NAME, 'td')
        
        player_score['name'] = tds[1].text
        player_score['round1'] = tds[2].text
        player_score['round2'] = tds[3].text
        player_score['round3'] = tds[4].text
        player_score['round4'] = tds[5].text
    
        scoreboard.append(player_score)
        
scoreboard

CPU times: user 878 ms, sys: 104 ms, total: 981 ms
Wall time: 16 s

[{'name': 'Jhonattan Vegas',
  'round1': '64',
  'round2': ' ',
  'round3': ' ',
  'round4': ' '},
 {'name': 'David Lipsky',
  'round1': '-7',
  'round2': ' ',
  'round3': ' ',
  'round4': ' '},
 {'name': 'Danny Lee',
  'round1': '65',
  'round2': ' ',
  'round3': ' ',
  'round4': ' '},
 {'name': 'Scott Stallings',
  'round1': '65',
  'round2': ' ',
  'round3': ' ',
  'round4': ' '},
 {'name': 'Richy Werenski',
  'round1': '65',
  'round2': ' ',
  'round3': ' ',
  'round4': ' '},
 {'name': 'Sam Burns',
  'round1': '-6',
  'round2': ' ',
  'round3': ' ',
  'round4': ' '},
 {'name': 'Kramer Hickok',
  'round1': '66',
  'round2': ' ',
  'round3': ' ',
  'round4': ' '},
 {'name': 'Doc Redman',
  'round1': '66',
  'round2': ' ',
  'round3': ' ',
  'round4': ' '},
 {'name': 'Justin Thomas',
  'round1': '66',
  'round2': ' ',
  'round3': ' ',
  'round4': ' '},
 {'name': 'Adam Hadwin',
  'round1': '-5',
  'round2': ' ',
  'round3': ' ',
  'round4': ' '},
 {'name': 'Davis Riley',
  'round1': '-5',
  'round2': ' ',
  'round3': ' ',
  'round4': ' '},
 {'name': 'Matthew NeSmith',
  'round1': '67',
  'round2': ' ',
  'round3': ' ',
  'round4': ' '},
 {'name': 'Brice Garnett',
  'round1': '67',
  'round2': ' ',
  'round3': ' ',
  'round4': ' '},
 {'name': 'Stewart Cink',
  'round1': '67',
  'round2': ' ',
  'round3': ' ',
  'round4': ' '},
 {'name': 'Dustin Johnson',
  'round1': '67',
  'round2': ' ',
  'round3': ' ',
  'round4': ' '},
 {'name': 'Brooks Koepka',
  'round1': '67',
  'round2': ' ',
  'round3': ' ',
  'round4': ' '},
 {'name': 'Louis Oosthuizen',
  'round1': '67',
  'round2': ' ',
  'round3': ' ',
  'round4': ' '},
 {'name': 'Matt Kuchar',
  'round1': '67',
  'round2': ' ',
  'round3': ' ',
  'round4': ' '},
 {'name': 'Chez Reavie',
  'round1': '67',
  'round2': ' ',
  'round3': ' ',
  'round4': ' '},
 {'name': 'Matthew Fitzpatrick',
  'round1': '67',
  'round2': ' ',
  'round3': ' ',
  'round4': ' '},
 {'name': 'J.J. Spaun',
  'round1': '67',
  'round2': ' ',
  'round3': ' ',
  'round4': ' '},
 {'name': 'Kevin Streelman',
  'round1': '67',
  'round2': ' ',
  'round3': ' ',
  'round4': ' '},
 {'name': 'Blake Kennedy',
  'round1': '67',
  'round2': ' ',
  'round3': ' ',
  'round4': ' '},
 {'name': 'Greyson Sigg',
  'round1': '67',
  'round2': ' ',
  'round3': ' ',
  'round4': ' '},
 {'name': 'Pat Perez',
  'round1': '67',
  'round2': ' ',
  'round3': ' ',
  'round4': ' '},
 {'name': 'Xander Schauffele',
  'round1': '-4',
  'round2': ' ',
  'round3': ' ',
  'round4': ' '},
 {'name': 'Webb Simpson',
  'round1': '-4',
  'round2': ' ',
  'round3': ' ',
  'round4': ' '},
 {'name': 'Gary Woodland',
  'round1': '-4',
  'round2': ' ',
  'round3': ' ',
  'round4': ' '},
 {'name': 'Tommy Fleetwood',
  'round1': '-4',
  'round2': ' ',
  'round3': ' ',
  'round4': ' '},
 {'name': 'Cameron Tringale',
  'round1': '68',
  'round2': ' ',
  'round3': ' ',
  'round4': ' '},
 {'name': 'Bubba Watson',
  'round1': '68',
  'round2': ' ',
  'round3': ' ',
  'round4': ' '},
 {'name': 'Collin Morikawa',
  'round1': '68',
  'round2': ' ',
  'round3': ' ',
  'round4': ' '},
 {'name': 'Wesley Bryan',
  'round1': '68',
  'round2': ' ',
  'round3': ' ',
  'round4': ' '},
 {'name': 'Jimmy Walker',
  'round1': '68',
  'round2': ' ',
  'round3': ' ',
  'round4': ' '},
 {'name': 'Luke Donald',
  'round1': '68',
  'round2': ' ',
  'round3': ' ',
  'round4': ' '},
 {'name': 'Alex Noren',
  'round1': '68',
  'round2': ' ',
  'round3': ' ',
  'round4': ' '},
 {'name': 'Austin Smotherman',
  'round1': '68',
  'round2': ' ',
  'round3': ' ',
  'round4': ' '},
 {'name': 'Troy Merritt',
  'round1': '68',
  'round2': ' ',
  'round3': ' ',
  'round4': ' '},
 {'name': 'Henrik Norlander',
  'round1': '68',
  'round2': ' ',
  'round3': ' ',
  'round4': ' '},
 {'name': 'Brian Stuard',
  'round1': '68',
  'round2': ' ',
  'round3': ' ',
  'round4': ' '},
 {'name': 'Wyndham Clark',
  'round1': '68',
  'round2': ' ',
  'round3': ' ',
  'round4': ' '},
 {'name': 'Joel Dahmen',
  'round1': '68',
  'round2': ' ',
  'round3': ' ',
  'round4': ' '},
 {'name': 'Andrew Landry',
  'round1': '68',
  'round2': ' ',
  'round3': ' ',
  'round4': ' '},
 {'name': 'William McGirt',
  'round1': '-3',
  'round2': ' ',
  'round3': ' ',
  'round4': ' '},
 {'name': 'Tyrrell Hatton',
  'round1': '-3',
  'round2': ' ',
  'round3': ' ',
  'round4': ' '},
 {'name': 'Robert Streb',
  'round1': '-3',
  'round2': ' ',
  'round3': ' ',
  'round4': ' '},
 {'name': 'Nick Taylor',
  'round1': '-3',
  'round2': ' ',
  'round3': ' ',
  'round4': ' '},
 {'name': 'Lee Hodges',
  'round1': '-3',
  'round2': ' ',
  'round3': ' ',
  'round4': ' '},
 {'name': 'Brian Harman',
  'round1': '-3',
  'round2': ' ',
  'round3': ' ',
  'round4': ' '},
 {'name': 'Paul Barjon',
  'round1': '-3',
  'round2': ' ',
  'round3': ' ',
  'round4': ' '},
 {'name': 'Sahith Theegala',
  'round1': '-3',
  'round2': ' ',
  'round3': ' ',
  'round4': ' '},
 {'name': 'Bernd Wiesberger',
  'round1': '-3',
  'round2': ' ',
  'round3': ' ',
  'round4': ' '},
 {'name': 'Kelly Kraft',
  'round1': '69',
  'round2': ' ',
  'round3': ' ',
  'round4': ' '},
 {'name': 'Denny McCarthy',
  'round1': '69',
  'round2': ' ',
  'round3': ' ',
  'round4': ' '},
 {'name': 'Sam Ryder',
  'round1': '69',
  'round2': ' ',
  'round3': ' ',
  'round4': ' '},
 {'name': 'Jim Herman',
  'round1': '69',
  'round2': ' ',
  'round3': ' ',
  'round4': ' '},
 {'name': 'Viktor Hovland',
  'round1': '69',
  'round2': ' ',
  'round3': ' ',
  'round4': ' '},
 {'name': 'Tyler Duncan',
  'round1': '69',
  'round2': ' ',
  'round3': ' ',
  'round4': ' '},
 {'name': 'Patton Kizzire',
  'round1': '69',
  'round2': ' ',
  'round3': ' ',
  'round4': ' '},
 {'name': 'J.T. Poston',
  'round1': '69',
  'round2': ' ',
  'round3': ' ',
  'round4': ' '},
 {'name': 'Kiradech Aphibarnrat',
  'round1': '69',
  'round2': ' ',
  'round3': ' ',
  'round4': ' '},
 {'name': 'Aaron Wise',
  'round1': '69',
  'round2': ' ',
  'round3': ' ',
  'round4': ' '},
 {'name': 'Martin Kaymer',
  'round1': '69',
  'round2': ' ',
  'round3': ' ',
  'round4': ' '},
 {'name': 'Mito Pereira',
  'round1': '69',
  'round2': ' ',
  'round3': ' ',
  'round4': ' '},
 {'name': 'Shane Lowry',
  'round1': '69',
  'round2': ' ',
  'round3': ' ',
  'round4': ' '},
 {'name': 'Harry Higgs',
  'round1': '-2',
  'round2': ' ',
  'round3': ' ',
  'round4': ' '},
 {'name': 'Matt Wallace',
  'round1': '-2',
  'round2': ' ',
  'round3': ' ',
  'round4': ' '},
 {'name': 'Joseph Bramlett',
  'round1': '-2',
  'round2': ' ',
  'round3': ' ',
  'round4': ' '},
 {'name': 'Hank Lebioda',
  'round1': '70',
  'round2': ' ',
  'round3': ' ',
  'round4': ' '},
 {'name': 'Seung-yul Noh',
  'round1': '70',
  'round2': ' ',
  'round3': ' ',
  'round4': ' '},
 {'name': 'Jason Day',
  'round1': '70',
  'round2': ' ',
  'round3': ' ',
  'round4': ' '},
 {'name': 'Abraham Ancer',
  'round1': '70',
  'round2': ' ',
  'round3': ' ',
  'round4': ' '},
 {'name': 'Brendon Todd',
  'round1': '70',
  'round2': ' ',
  'round3': ' ',
  'round4': ' '},
 {'name': 'Danny Willett',
  'round1': '70',
  'round2': ' ',
  'round3': ' ',
  'round4': ' '},
 {'name': 'Keegan Bradley',
  'round1': '70',
  'round2': ' ',
  'round3': ' ',
  'round4': ' '},
 {'name': 'Christiaan Bezuidenhout',
  'round1': '70',
  'round2': ' ',
  'round3': ' ',
  'round4': ' '},
 {'name': 'Alex Smalley',
  'round1': '70',
  'round2': ' ',
  'round3': ' ',
  'round4': ' '},
 {'name': 'Dylan Wu',
  'round1': '70',
  'round2': ' ',
  'round3': ' ',
  'round4': ' '},
 {'name': 'Tommy Gainey',
  'round1': '70',
  'round2': ' ',
  'round3': ' ',
  'round4': ' '},
 {'name': 'James Hahn',
  'round1': '70',
  'round2': ' ',
  'round3': ' ',
  'round4': ' '},
 {'name': 'Mark Hensby',
  'round1': '70',
  'round2': ' ',
  'round3': ' ',
  'round4': ' '},
 {'name': 'Kevin Kisner',
  'round1': '70',
  'round2': ' ',
  'round3': ' ',
  'round4': ' '},
 {'name': 'Henrik Stenson',
  'round1': '70',
  'round2': ' ',
  'round3': ' ',
  'round4': ' '},
 {'name': 'Adam Long',
  'round1': '-1',
  'round2': ' ',
  'round3': ' ',
  'round4': ' '},
 {'name': 'Greg Koch',
  'round1': '-1',
  'round2': ' ',
  'round3': ' ',
  'round4': ' '},
 {'name': 'Andrew McCain',
  'round1': '-1',
  'round2': ' ',
  'round3': ' ',
  'round4': ' '},
 {'name': 'Jackson Suber',
  'round1': '-1',
  'round2': ' ',
  'round3': ' ',
  'round4': ' '},
 {'name': 'Curtis Thompson',
  'round1': '-1',
  'round2': ' ',
  'round3': ' ',
  'round4': ' '},
 {'name': 'Peter Malnati',
  'round1': '71',
  'round2': ' ',
  'round3': ' ',
  'round4': ' '},
 {'name': 'Roger Sloan',
  'round1': '71',
  'round2': ' ',
  'round3': ' ',
  'round4': ' '},
 {'name': 'Jason Kokrak',
  'round1': '71',
  'round2': ' ',
  'round3': ' ',
  'round4': ' '},
 {'name': 'Branden Grace',
  'round1': '71',
  'round2': ' ',
  'round3': ' ',
  'round4': ' '},
 {'name': 'Ryan Brehm',
  'round1': '71',
  'round2': ' ',
  'round3': ' ',
  'round4': ' '},
 {'name': 'Nate Lashley',
  'round1': '71',
  'round2': ' ',
  'round3': ' ',
  'round4': ' '},
 {'name': 'C.T. Pan',
  'round1': '71',
  'round2': ' ',
  'round3': ' ',
  'round4': ' '},
 {'name': 'Bill Haas',
  'round1': '71',
  'round2': ' ',
  'round3': ' ',
  'round4': ' '},
 {'name': 'Mackenzie Hughes',
  'round1': '71',
  'round2': ' ',
  'round3': ' ',
  'round4': ' '},
 {'name': 'Alex Fitzpatrick',
  'round1': '71',
  'round2': ' ',
  'round3': ' ',
  'round4': ' '},
 {'name': 'John Huh',
  'round1': '71',
  'round2': ' ',
  'round3': ' ',
  'round4': ' '},
 {'name': 'Carlos Ortiz',
  'round1': '71',
  'round2': ' ',
  'round3': ' ',
  'round4': ' '},
 {'name': 'Russell Knox',
  'round1': 'E',
  'round2': ' ',
  'round3': ' ',
  'round4': ' '},
 {'name': 'Brandon Hagy',
  'round1': 'E',
  'round2': ' ',
  'round3': ' ',
  'round4': ' '},
 {'name': 'Seth Reeves',
  'round1': 'E',
  'round2': ' ',
  'round3': ' ',
  'round4': ' '},
 {'name': 'Taylor Moore',
  'round1': 'E',
  'round2': ' ',
  'round3': ' ',
  'round4': ' '},
 {'name': 'Lanto Griffin',
  'round1': '72',
  'round2': ' ',
  'round3': ' ',
  'round4': ' '},
 {'name': 'Martin Trainer',
  'round1': '72',
  'round2': ' ',
  'round3': ' ',
  'round4': ' '},
 {'name': 'Adam Schenk',
  'round1': '72',
  'round2': ' ',
  'round3': ' ',
  'round4': ' '},
 {'name': 'Brandon Wu',
  'round1': '72',
  'round2': ' ',
  'round3': ' ',
  'round4': ' '},
 {'name': 'Kevin Yu',
  'round1': '72',
  'round2': ' ',
  'round3': ' ',
  'round4': ' '},
 {'name': 'Hayden Buckley',
  'round1': '72',
  'round2': ' ',
  'round3': ' ',
  'round4': ' '},
 {'name': 'Michael Thompson',
  'round1': '72',
  'round2': ' ',
  'round3': ' ',
  'round4': ' '},
 {'name': 'Matthias Schwab',
  'round1': '+1',
  'round2': ' ',
  'round3': ' ',
  'round4': ' '},
 {'name': 'Luke Guthrie',
  'round1': '+1',
  'round2': ' ',
  'round3': ' ',
  'round4': ' '},
 {'name': 'Max McGreevy',
  'round1': '+1',
  'round2': ' ',
  'round3': ' ',
  'round4': ' '},
 {'name': 'Adam Svensson',
  'round1': '+1',
  'round2': ' ',
  'round3': ' ',
  'round4': ' '},
 {'name': 'Chesson Hadley',
  'round1': '73',
  'round2': ' ',
  'round3': ' ',
  'round4': ' '},
 {'name': "Sean O'Hair",
  'round1': '73',
  'round2': ' ',
  'round3': ' ',
  'round4': ' '},
 {'name': 'Scott Piercy',
  'round1': '73',
  'round2': ' ',
  'round3': ' ',
  'round4': ' '},
 {'name': 'Davis Love III',
  'round1': '73',
  'round2': ' ',
  'round3': ' ',
  'round4': ' '},
 {'name': 'Zach Johnson',
  'round1': '73',
  'round2': ' ',
  'round3': ' ',
  'round4': ' '},
 {'name': 'Jonas Blixt',
  'round1': '73',
  'round2': ' ',
  'round3': ' ',
  'round4': ' '},
 {'name': 'Kyle Stanley',
  'round1': '73',
  'round2': ' ',
  'round3': ' ',
  'round4': ' '},
 {'name': 'Brian Gay',
  'round1': '73',
  'round2': ' ',
  'round3': ' ',
  'round4': ' '},
 {'name': 'Graeme McDowell',
  'round1': '73',
  'round2': ' ',
  'round3': ' ',
  'round4': ' '},
 {'name': 'Sung Kang',
  'round1': '+2',
  'round2': ' ',
  'round3': ' ',
  'round4': ' '},
 {'name': 'Harold Varner III',
  'round1': '+2',
  'round2': ' ',
  'round3': ' ',
  'round4': ' '},
 {'name': 'Charl Schwartzel',
  'round1': '+2',
  'round2': ' ',
  'round3': ' ',
  'round4': ' '},
 {'name': 'Emiliano Grillo',
  'round1': '+2',
  'round2': ' ',
  'round3': ' ',
  'round4': ' '},
 {'name': 'Vaughn Taylor',
  'round1': '+2',
  'round2': ' ',
  'round3': ' ',
  'round4': ' '},
 {'name': 'Andrew Novak',
  'round1': '+2',
  'round2': ' ',
  'round3': ' ',
  'round4': ' '},
 {'name': 'Andrew Putnam',
  'round1': '74',
  'round2': ' ',
  'round3': ' ',
  'round4': ' '},
 {'name': 'Austin Cook',
  'round1': '74',
  'round2': ' ',
  'round3': ' ',
  'round4': ' '},
 {'name': 'Vincent Whaley',
  'round1': '74',
  'round2': ' ',
  'round3': ' ',
  'round4': ' '},
 {'name': 'Martin Laird',
  'round1': '+3',
  'round2': ' ',
  'round3': ' ',
  'round4': ' '},
 {'name': 'Trey Mullinax',
  'round1': '75',
  'round2': ' ',
  'round3': ' ',
  'round4': ' '},
 {'name': 'Callum Tarren',
  'round1': '75',
  'round2': ' ',
  'round3': ' ',
  'round4': ' '},
 {'name': 'Chad Ramey',
  'round1': '75',
  'round2': ' ',
  'round3': ' ',
  'round4': ' '},
 {'name': 'Kurt Kitayama',
  'round1': '+4',
  'round2': ' ',
  'round3': ' ',
  'round4': ' '},
 {'name': 'Bronson Burgoon',
  'round1': '76',
  'round2': ' ',
  'round3': ' ',
  'round4': ' '},
 {'name': 'Stephan Jaeger',
  'round1': '76',
  'round2': ' ',
  'round3': ' ',
  'round4': ' '},
 {'name': 'Cameron Percy',
  'round1': '76',
  'round2': ' ',
  'round3': ' ',
  'round4': ' '},
 {'name': 'Francesco Molinari',
  'round1': '+5',
  'round2': ' ',
  'round3': ' ',
  'round4': ' '},
 {'name': 'Charley Hoffman',
  'round1': '+5',
  'round2': ' ',
  'round3': ' ',
  'round4': ' '},
 {'name': 'Omar Uresti',
  'round1': '78',
  'round2': ' ',
  'round3': ' ',
  'round4': ' '}]

In [12]:
import pandas as pd

OpenBLAS WARNING - could not determine the L2 cache size on this system, assuming 256k

In [114]:
df = pd.DataFrame(scoreboard)

df

                   name round1 round2 round3 round4
0       Jhonattan Vegas     64
1          David Lipsky     -7
2             Danny Lee     65
3       Scott Stallings     65
4        Richy Werenski     65
..                  ...    ...    ...    ...    ...
139      Stephan Jaeger     76
140       Cameron Percy     76
141  Francesco Molinari     +5
142     Charley Hoffman     +5
143         Omar Uresti     78

[144 rows x 5 columns]

In [115]:
df.set_index('name', inplace=True)

In [116]:
df.round1.unique()

array(['64', '-7', '65', '-6', '66', '-5', '67', '-4', '68', '-3', '69',
       '-2', '70', '-1', '71', 'E', '72', '+1', '73', '+2', '74', '+3',
       '75', '+4', '76', '+5', '78'], dtype=object)

In [117]:
def convert_to_plus_minus(score: str, par: int):
    return int(score) - par

convert_to_plus_minus('64', 71)

-7

In [118]:
int('-5') + int('+5')

0

In [119]:
def convert_even():
    return 0

In [129]:
def clean_up_distributor(score, par):
    if isinstance(score, int):
        return score
    elif score == 'E':
        return convert_even()
    elif '+' in score or '-' in score:
        return int(score)
    elif score == ' ':
        return 0
    elif isinstance(score, str):
        return convert_to_plus_minus(score, par)
    else:
        print('method not implemented')
        
print(clean_up_distributor('E', 71))
print(clean_up_distributor('+7', 71))
print(clean_up_distributor('72', 71))

0
7
1

In [130]:
df

                   round1  round2  round3  round4
name
Jhonattan Vegas        -7       0       0       0
David Lipsky           -7       0       0       0
Danny Lee              -6       0       0       0
Scott Stallings        -6       0       0       0
Richy Werenski         -6       0       0       0
...                   ...     ...     ...     ...
Stephan Jaeger          5       0       0       0
Cameron Percy           5       0       0       0
Francesco Molinari     +5       0       0       0
Charley Hoffman        +5       0       0       0
Omar Uresti             7       0       0       0

[144 rows x 4 columns]

In [131]:
def update_columns(df, par):
    for col in df.columns:
        df[col] = df[col].apply(lambda x: clean_up_distributor(x, par))
        
update_columns(df, 71)

In [132]:
df

                    round1  round2  round3  round4
name
Jhonattan Vegas         -7       0       0       0
David Lipsky            -7       0       0       0
Danny Lee               -6       0       0       0
Scott Stallings         -6       0       0       0
Richy Werenski          -6       0       0       0
...                    ...     ...     ...     ...
Stephan Jaeger           5       0       0       0
Cameron Percy            5       0       0       0
Francesco Molinari       5       0       0       0
Charley Hoffman          5       0       0       0
Omar Uresti              7       0       0       0

[144 rows x 4 columns]

In [137]:
def create_total_col(df):
    df['total'] = df['round1']+df['round2']+df['round3']+df['round4']
    
    return df

In [138]:
df = create_total_col(df)

In [139]:
df

                    round1  round2  round3  round4  total
name
Jhonattan Vegas         -7       0       0       0     -7
David Lipsky            -7       0       0       0     -7
Danny Lee               -6       0       0       0     -6
Scott Stallings         -6       0       0       0     -6
Richy Werenski          -6       0       0       0     -6
...                    ...     ...     ...     ...    ...
Stephan Jaeger           5       0       0       0      5
Cameron Percy            5       0       0       0      5
Francesco Molinari       5       0       0       0      5
Charley Hoffman          5       0       0       0      5
Omar Uresti              7       0       0       0      7

[144 rows x 5 columns]